export const cartTypes = {
    CREATE_TABLE: 'CREATE_TABLE',

    FETCH_PRODUCTS_FROM_CART: 'FETCH_PRODUCTS_FROM_CART',
    FETCH_PRODUCTS_FROM_CART_FAILED: 'FETCH_PRODUCTS_FROM_CART_FAILED',
    FETCH_PRODUCTS_FROM_CART_SUCCESS: 'FETCH_PRODUCTS_FROM_CART_SUCCESS',

    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    ADD_PRODUCT_TO_CART_SUCCESS: 'ADD_PRODUCT_TO_CART_SUCCESS',
    ADD_PRODUCT_TO_CART_FAILED: 'ADD_PRODUCT_TO_CART_FAILED',

    REMOVE_PRODUCT_FROM_CART:'REMOVE_PRODUCT_FROM_CART',
    REMOVE_PRODUCT_FROM_CART_SUCCESS:'REMOVE_PRODUCT_FROM_CART_SUCCESS',
    REMOVE_PRODUCT_FROM_CART_FAILED:'REMOVE_PRODUCT_FROM_CART_FAILED',
}