export const productTypes = {
    PRODUCT_FETCH_ALL: 'PRODUCT_FETCH_ALL',
    PRODUCT_FETCH_ALL_FAILED: 'PRODUCT_FETCH_ALL_FAILED',
    PRODUCT_FETCH_ALL_SUCCESS: 'PRODUCT_FETCH_ALL_SUCCESS',
    PRODUCT_FETCH_ALL_RESET: 'PRODUCT_FETCH_ALL_RESET',

    PRODUCT_CATEGORY_FETCH: 'PRODUCT_CATEGORY_FETCH',
    PRODUCT_CATEGORY_FETCH_FAILED: 'PRODUCT_CATEGORY_FETCH_FAILED',
    PRODUCT_CATEGORY_FETCH_SUCCESS: 'PRODUCT_CATEGORY_FETCH_SUCCESS',
    PRODUCT_CATEGORY_RESET: 'PRODUCT_CATEGORY_RESET',
    
    PRODUCT_FETCH_ONE: 'PRODUCT_FETCH_ONE',
    PRODUCT_FETCH_ONE_FAILED: 'PRODUCT_FETCH_ONE_FAILED',
    PRODUCT_FETCH_ONE_SUCCESS: 'PRODUCT_FETCH_ONE_SUCCESS',
    PRODUCT_FETCH_ONE_RESET: 'PRODUCT_FETCH_ONE_RESET',
    
    PRODUCT_FETCH_BY_CATEGORY: 'PRODUCT_FETCH_BY_CATEGORY',
    PRODUCT_FETCH_BY_CATEGORY_FAILED: 'PRODUCT_FETCH_BY_CATEGORY_FAILED',
    PRODUCT_FETCH_BY_CATEGORY_SUCCESS: 'PRODUCT_FETCH_BY_CATEGORY_SUCCESS',
    PRODUCT_FETCH_BY_CATEGORY_RESET: 'PRODUCT_FETCH_BY_CATEGORY_RESET',
    PRODUCT_UPDATE_CATEGORY: 'PRODUCT_UPDATE_CATEGORY'
}